In [3]:
import numpy as np 
a=np.array([1,2,3,4]);
print(a*10)

[10 20 30 40]


In [5]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]]);
print(a.T)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [87]:
import numpy as np
a=np.array([10,2,20,30])
print(np.random.rand(5))
print (np.random.choice(a))
print(np.random.randint(a))

[0.91643986 0.37254306 0.76364777 0.66485948 0.90633377]
20
[ 1 13  3  7]


In [91]:
# reshapeing the array
import numpy as np
a=np.arange(12);
print(a.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [98]:
# axis  axis =0(coloumns axis=1(rows sum))
import numpy as np
a=np.arange(12)
b=a.reshape(3,4)
print(a.reshape(3,4))
print(np.sum(b,axis=1))
print(np.sum(b,axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 6 22 38]
[12 15 18 21]


In [101]:
import numpy as np
a=np.arange(12)
result=np.where(a<5,1,a)
print(result)

[ 1  1  1  1  1  5  6  7  8  9 10 11]


In [102]:
import numpy as np
a=np.arange(12)
m=np.mean(a)
result=np.where(a<m,1,a)
print(result)

[ 1  1  1  1  1  1  6  7  8  9 10 11]
