In [52]:
import numpy as np 
a =np.array([1,2,3,4])
b=a.copy();
b[2]=44
print(b(b>2))
# slicing
# copying 

TypeError: 'numpy.ndarray' object is not callable

In [51]:
import numpy as np
ar=np.array([1,2,3,4,4])
print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))
print(np.mean(arr))
print(np.sum(arr))

[[1.         1.41421356 1.73205081 2.         2.23606798]
 [3.46410162 5.83095189 2.23606798 2.44948974 8.06225775]]
[[0.         0.69314718 1.09861229 1.38629436 1.60943791]
 [2.48490665 3.52636052 1.60943791 1.79175947 4.17438727]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
  1.48413159e+02]
 [1.62754791e+05 5.83461743e+14 1.48413159e+02 4.03428793e+02
  1.69488924e+28]]
65
1
19.401288616996553
13.7
137


In [55]:
import numpy as np
arr=np.array([1,2,3])
arr1=np.array([1,2,3])
print(np.dot(arr,arr1))

14


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5]);
print(a*10)

In [44]:
import numpy as np
a=np.array([[1,2,3],[6,7,8],[4,5,6]])
b=np.array([[1,2,3],[6,7,8],[7,9,6]])
print(a.size)
print(a.shape)
print(a.ndim)
print(np.dot(a,b));

9
(3, 3)
2
[[ 34  43  37]
 [104 133 122]
 [ 76  97  88]]


In [47]:
import numpy as np
arr=np.array([[1,2,3,4,5],[12,34,5,6,65]])
print(arr.mat[1,2])

AttributeError: 'numpy.ndarray' object has no attribute 'mat'

In [23]:
import numpy as np
a=np.arange(1,8,2)
print(a)

[1 3 5 7]
