In [90]:
!pip install numpy

In [91]:
import numpy as np

In [92]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [93]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [94]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [95]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [96]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Range of Numbers

In [97]:
np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

Evenly Spaced Numbers

In [99]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Array Properties


In [100]:
arr= np.array([[1,2,3],
               [4,5,6]])

In [101]:
print(arr.ndim) # number of dimensions
print(arr.shape) # shape of the array
print(arr.size)  # total number of elements
print(arr.dtype) # data type of the elements

2
(2, 3)
6
int32


Type Conversion 

In [102]:
arr=np.array([1,2,3,4,5,6])
print(arr[0]) #indexing
print(arr[-1]) #indexing


1
6


1D Slicing

In [103]:
arr=np.array([1,2,3,4,5,6])
print(arr[1:3])
print(arr[::2])
print(arr[:2])

[2 3]
[1 3 5]
[1 2]


2D Slicing


In [104]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat[0,1]) #slicing
print(mat[2])
print(mat[:, 2])

2
[7 8 9]
[3 6 9]


In [105]:
c=np.array([1,2,3,4,5,6])
d=c.copy() # copy
c[0]=99 
print(c)
print(d)

[99  2  3  4  5  6]
[1 2 3 4 5 6]


Basic Array operations (VECTOR POWER)

In [106]:
a=np.array([1,2,3])
b=np.array([4,5,6])

print(a+b)  # element-wise addition 
print(a-b)  # element-wise subtraction
print(a/b)  # element-wise division
print(a*b)  # element-wise multiplication
print(a**2) # element-wise exponentiation

[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[ 4 10 18]
[1 4 9]


Scaler Operation

In [107]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+10)
print(a*2)

[11 12 13]
[2 4 6]


Unfus (UNIVERSAL FUNCTIONS)

In [108]:
arr = np.array([1,3,4,5,6])

Boolean Indexing

In [109]:
arr= np.array([11,21,31,41,51,61,17,18,19])
print(arr[arr>25])  # conditional filtering
print(arr>25)

[31 41 51 61]
[False False  True  True  True  True False False False]


In [110]:
mat = np.array([[1,2,3],
                [4,5,6]])
print(mat+10)

[[11 12 13]
 [14 15 16]]


Matrix Multiplication

In [111]:
A = np.array([[1,2],[3,4]])
B =  np.array([[5,6],[7,8]])
print(np.dot(A,B))


[[19 22]
 [43 50]]


In [112]:
print(A.T) # transpose

[[1 3]
 [2 4]]


Random Module

In [113]:
np.random.rand(5) # random numbers between 0 and 1


array([0.14664342, 0.90416481, 0.4260288 , 0.19487102, 0.34857305])

In [114]:
np.random.rand(3,3) # random numbers in a 3x3 matrix

array([[0.89336496, 0.81530474, 0.37551853],
       [0.56797715, 0.59868581, 0.65361627],
       [0.20571616, 0.36299424, 0.09509255]])

In [115]:
np.random.randint(1,120,10) # random integers between 1 and 100, total 10 numbers

array([  2, 117,  67,  92,  97,   6,  60,  31, 106, 117])

Reshaping Arrays

In [116]:
arr=np.arange(12)
print(arr.reshape(3,4)) # reshape

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Axis in NumPy

In [117]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(np.sum(arr)) # sum of all elements
print(np.sum(arr, axis=0)) # sum of each column 
print(np.sum(arr, axis=1)) # sum of each row

[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]


"Where" in NumPy

In [127]:
arr=np.array([1,-2,3,-4,5])
result1 = np.where(arr<0,0,arr) # replace negative numbers with 0
print(result1)
result2 = np.where(arr % 2!=0,-1,arr) # replace even numbers with -1
print(result2)

[1 0 3 0 5]
[-1 -2 -1 -4 -1]


In [132]:
data=np.array([10,20,30,40,50,60,70,80,90])
mean_val=np.mean(data) # mean of all elements
result=np.where(data>mean_val,mean_val,data)# replace elements greater than mean with mean value
print(result)

[10. 20. 30. 40. 50. 50. 50. 50. 50.]


Applying "Where" condition in 2D array

In [ ]:
mat=np.array([[10,20,30],[40,50,60],[70,80,90]])
result = np.where(mat>=50,1,0) # binary mask for elements greater than or equal to 50
print(result)               

[[0 0 0]
 [0 1 1]
 [1 1 1]]
